#!/bin/sh
### BEGIN INIT INFO
# Provides:             iptables_rules
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    firewall
### END INIT INFO
sudo /home/pi/mp751/mp751_POFF
